# general.import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]
general.import = ["~/.config/alacritty/themes/darcula_dark.toml"]
general.live_config_reload = true

[terminal.shell]
program = "/bin/zsh"

[font]
size = 12.0

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"

[window]
decorations = "full"
padding = { x = 5, y = 5 }
opacity = 1.00
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 80
lines = 30

[scrolling]
history = 10_000
multiplier = 3

[cursor]
style.shape = "Block"

## #######################################
# keybindings
[[keyboard.bindings]]
key = "C"
mods = "Command|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Command|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "U"
mods = "Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "D"
mods = "Alt"
action = "ScrollPageDown"
